// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test methods cant be static", Scope = "member", Target = "~M:MetadataScanner.Tests.TestScanner.TestScannerFindsSomeAssemblies")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test methods cant be static", Scope = "member", Target = "~M:MetadataScanner.Test.TestScanner.TestScannerFindsSomeAssemblies")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancies in Symbol Declarations", "RECS0154:Parameter is never used", Justification = "This is a file that isn't actually written by me", Scope = "type", Target = "~T:AutoGeneratedProgram")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test methods cant be static", Scope = "member", Target = "~M:MetadataScanner.Test.TestScanner.TestDummyAssemblyContainsSomeAssemblyReferences")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test methods cant be static", Scope = "member", Target = "~M:MetadataScanner.Test.TestScanner.TestDummyAssemblyContainsSomeDefinedTypes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test methods cant be static>", Scope = "member", Target = "~M:MetadataScanner.Test.TestScanner.TestDummyAssemblyContainsSomeTypeReferences")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test methods cant be static", Scope = "member", Target = "~M:MetadataScanner.Test.TestScanner.TestScannerFindsTheDummyAssembly")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test methods cant be static", Scope = "member", Target = "~M:MetadataScanner.Test.TestScanner.TestThatIRegistryShouldBeMarkedAsAnInterface")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test methods cant be static", Scope = "member", Target = "~M:MetadataScanner.Test.TestScanner.TestThatMySimpleRegistryImplementsIRegistry")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Test methods cant be static", Scope = "member", Target = "~M:MetadataScanner.Test.TestScanner.TestThatRegistryImplementsIRegistry")]